export const BUILDING_GROUND_OVERLAP_METERS = 1;
export const BUILDING_ROOF_TRIM_METERS = 0.32;
export const BUILDING_ROOF_OVERHANG_METERS = 0.45;
export const BUILDING_ROOF_EAVE_CLEARANCE_METERS = 0.2;
export const BUILDING_WALL_THICKNESS_METERS = 0.24;
export const BUILDING_FLOOR_THICKNESS_METERS = 0.16;
export const BUILDING_DOOR_WIDTH_METERS = 1.35;
export const BUILDING_DOOR_HEIGHT_METERS = 2.2;
export const BUILDING_WINDOW_EDGE_CLEARANCE_METERS = 0.08;
export const BUILDING_WINDOW_HEAD_CLEARANCE_METERS = 0.3;
export const BUILDING_WINDOW_CLEAR_DISTANCE_METERS = 9;
export const BUILDING_WINDOW_OPAQUE_DISTANCE_METERS = 18;
export const BUILDING_WINDOW_CLOSE_ALPHA = 0.16;
export const BUILDING_REFLECTIVE_MARKER_ALPHA = 0.72;

export const BUILDING_INTERIOR_LOAD_DISTANCE_METERS = 18;
export const BUILDING_INTERIOR_UNLOAD_DISTANCE_METERS = 27;
export const BUILDING_INTERIOR_CHECK_INTERVAL_MS = 120;
export const BUILDING_INTERIORS_PER_CHECK = 2;
/** Maximum number of adjacent interior storeys kept resident per building. */
export const BUILDING_INTERIOR_RENDERED_FLOOR_COUNT = 5;

export const BUILDING_STAIR_WIDTH_METERS = 1.15;
export const BUILDING_STAIR_MIN_RUN_METERS = 2.4;
export const BUILDING_STAIR_MAX_RUN_METERS = 4.2;
export const BUILDING_STAIR_WALL_CLEARANCE_METERS = 0.42;
